name: Terraform Azure Deployment

on:
  workflow_dispatch:
    inputs:
      auto_apply:
        description: 'Automatically apply Terraform changes after planning'
        required: false
        default: 'false'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      # Step 3: Parse Azure SP JSON
      - name: Parse Azure SP JSON
        run: |
          SP_JSON='${{ secrets.AZURE_SP_JSON }}'
          echo "TF_VAR_client_id=$(echo $SP_JSON | jq -r '.clientId')" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=$(echo $SP_JSON | jq -r '.clientSecret')" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=$(echo $SP_JSON | jq -r '.subscriptionId')" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=$(echo $SP_JSON | jq -r '.tenantId')" >> $GITHUB_ENV
          echo "TF_VAR_domeneshop_api_token=${{ secrets.DOMENESHOP_API_TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_domeneshop_api_secret=${{ secrets.DOMENESHOP_API_SECRET }}" >> $GITHUB_ENV

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./Terraform

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./Terraform
        env:
          TF_VAR_client_id: ${{ env.TF_VAR_client_id }}
          TF_VAR_client_secret: ${{ env.TF_VAR_client_secret }}
          TF_VAR_subscription_id: ${{ env.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ env.TF_VAR_tenant_id }}
          TF_VAR_domeneshop_api_token: ${{ env.TF_VAR_domeneshop_api_token }}
          TF_VAR_domeneshop_api_secret: ${{ env.TF_VAR_domeneshop_api_secret }}

      # Step 6: Upload tfplan as an artifact
      - name: Upload tfplan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ./Terraform/tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download tfplan artifact
      - name: Download tfplan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ./Terraform

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      # Step 4: Parse Azure SP JSON (again, to load the variables)
      - name: Parse Azure SP JSON
        run: |
          SP_JSON='${{ secrets.AZURE_SP_JSON }}'
          echo "TF_VAR_client_id=$(echo $SP_JSON | jq -r '.clientId')" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=$(echo $SP_JSON | jq -r '.clientSecret')" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=$(echo $SP_JSON | jq -r '.subscriptionId')" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=$(echo $SP_JSON | jq -r '.tenantId')" >> $GITHUB_ENV
          echo "TF_VAR_domeneshop_api_token=${{ secrets.DOMENESHOP_API_TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_domeneshop_api_secret=${{ secrets.DOMENESHOP_API_SECRET }}" >> $GITHUB_ENV

      # Step 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./Terraform
        env:
          TF_VAR_client_id: ${{ env.TF_VAR_client_id }}
          TF_VAR_client_secret: ${{ env.TF_VAR_client_secret }}
          TF_VAR_subscription_id: ${{ env.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ env.TF_VAR_tenant_id }}
          TF_VAR_domeneshop_api_token: ${{ env.TF_VAR_domeneshop_api_token }}
          TF_VAR_domeneshop_api_secret: ${{ env.TF_VAR_domeneshop_api_secret }}